services:
  - type: web
    name: socio-backend
    env: node
    buildCommand: cd backend && npm install && pip install -r requirements.txt
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLOUD_CREDENTIALS_BASE64
        sync: false # This means you'll set it manually in the Render dashboard